name: "Build and push images"

on:
  push:
    branches:
      - "release"

jobs:
  Building:
    runs-on: ubuntu-latest
    name: "Build image"
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_USERNAME }}/nezha-argo:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Push images to Docker hub
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}
